/*
 * Randomness, imported for its side effect and imported first.
 *
 * @noble asks for `crypto.getRandomValues`, the way every well-behaved crypto
 * library does. Hermes does not have it — React Native's `global.crypto` is
 * either absent or a shell with `getRandomValues` missing — so the private key
 * this app's whole pairing rests on would be generated by a call that throws.
 *
 * expo-crypto is a native module over the platform CSPRNG, which is the right
 * source. This installs it, once, and refuses to overwrite a real one if the
 * runtime turns out to have shipped its own.
 *
 * It is imported at the top of `app/_layout.tsx`, above everything: a module
 * that reads `crypto` at import time (rather than at call time) would find it
 * missing if this ran second, and the failure would be a blank screen with a
 * message about a property of undefined.
 */
import { getRandomValues } from "expo-crypto";

type WithCrypto = { crypto?: { getRandomValues?: unknown } };
const g = globalThis as unknown as WithCrypto;

if (!g.crypto) {
  Object.defineProperty(globalThis, "crypto", { value: {}, configurable: true, writable: true });
}
if (typeof g.crypto?.getRandomValues !== "function") {
  // Not `crypto = { getRandomValues }`: on some Hermes builds `global.crypto`
  // exists and carries other things, and replacing the object drops them.
  (g.crypto as { getRandomValues: typeof getRandomValues }).getRandomValues = getRandomValues;
}

/** True when a secure source is in place. The pairing screen checks it before
 *  offering to generate a key, so a runtime without one says so up front
 *  instead of failing at the moment somebody has typed six digits. */
export function randomnessReady(): boolean {
  try {
    const probe = new Uint8Array(8);
    (g.crypto as { getRandomValues: (a: Uint8Array) => Uint8Array }).getRandomValues(probe);
    return probe.some((b) => b !== 0);
  } catch {
    return false;
  }
}
